### ISSUE TITLE
game default map 

### ISSUE THREAD

**Issue by tinysn0w** [GetStream/stream-chat-unreal#87]
hello
i run project in visual studio, but its gone blank. i found the default entry is incorrect finally.
then i mod setting files
[/Script/EngineSettings.GameMapsSettings]
and change 
GameDefaultMap=/Engine/Maps/Entry.Entry          
to
GameDefaultMap=/Game/TeamChatSample/Maps/TeamChatSample.TeamChatSample
it's run perfectly

**Comment by jeevcat** [comment]
Hi, thanks for trying out the plugin. We've purposely set up the sample project to package with a blank map. This makes it easier to swap in the CD workflow.

It might make more sense to have a different default. I'll fix this up next week.

Note that this doesn't affect the Plugin in any way.

**Comment by tinysn0w** [comment]
thanks
